### PR TITLE
Optional Install by HACS + Updated Docs

### PR DESCRIPTION
**Pull request by rsnodgrass**
* updated docs, including link to support thread
* added configuration for installation via HACS
* moved code into custom_components/chargepoint subdirectory to follow common HASS integration convention

### CODE REVIEW

**Comment by rsnodgrass** [comment]
@drynish can you review this?  Thanks.

**Comment by drynish** [comment]
Damn I didn't saw your update... :) Thanks for the feedback

**Comment by rsnodgrass** [comment]
@drynish I have merged in all your latest changes, can you please merge this into your branch?  Thanks!

**Comment by drynish** [comment]
Sorry it's my first foss project so I'm still learning collaborating! :)

**Pull request merged**
